version: '2'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: shop_os
    hostname: shop_os
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: shop_os_dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://shop_os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-config:/data/configdb
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb-config:
  mongodb-data: