package com.vr61v.SpringShoppingBot.entity;

public enum UserState {

    CATEGORY_WAITING_CREATE_REQUEST,
    VENDOR_WAITING_CREATE_REQUEST, PRODUCT_WAITING_DELETE_REQUEST, CATEGORY_WAITING_DELETE_REQUEST, VENDOR_WAITING_DELETE_REQUEST, PRODUCT_WAITING_CREATE_REQUEST

}
