package com.vr61v.SpringShoppingBot.entity;

public enum UserState {

    PRODUCT_WAITING_CREATE_REQUEST,
    PRODUCT_WAITING_UPDATE_REQUEST,
    PRODUCT_WAITING_SEARCH_REQUEST,
    PRODUCT_WAITING_DELETE_REQUEST,

    CATEGORY_WAITING_CREATE_REQUEST,
    CATEGORY_WAITING_UPDATE_REQUEST,
    CATEGORY_WAITING_SEARCH_REQUEST,
    CATEGORY_WAITING_DELETE_REQUEST,

    VENDOR_WAITING_CREATE_REQUEST,
    VENDOR_WAITING_UPDATE_REQUEST,
    VENDOR_WAITING_SEARCH_REQUEST,
    VENDOR_WAITING_DELETE_REQUEST, PRODUCT_WAITING_ADD_TO_BUCKET_REQUEST, PRODUCT_WAITING_ADD_TO_CART_REQUEST, CART_WAITING_TO_ADD_PRODUCT, CART_WAITING_REMOVE_FROM, CART_WAITING_ADD_TO,

}
